name: dex_collection
description: "Personal pokemon collection manager"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+2

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  logging: ^1.3.0
  go_router: ^15.1.2
  flutter_localizations:
    sdk: flutter
  intl: any 
  flutter_gen: ^5.10.0
  http: ^1.4.0
  logger: ^2.5.0
  hive_ce: ^2.11.3
  flutter_colorpicker: ^1.1.0
  uuid: ^4.5.1
  cached_network_image: ^3.4.1
  flex_color_picker: ^3.7.1
  flutter_download_manager: ^0.5.5
  flutter_svg: ^2.2.0
  hive_ce_flutter: ^2.3.1
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.4.15
  riverpod_lint: ^2.5.0
  hive_ce_generator: ^1.9.2
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/app/

flutter_intl: 
  enabled: false

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app/icon.png"
  remove_alpha_ios: true
  adaptive_icon_foreground: "assets/app/icon.png"
  adaptive_icon_background: "#ffbc00"
  adaptive_icon_foreground_inset: 17