// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:dex_collection/Hive/collected_pokemon/model/collected_pokemon.dart';
import 'package:dex_collection/Hive/collection/model/collection.dart';
import 'package:dex_collection/Hive/pokemon/model/pokemon.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CollectedPokemonAdapter());
    registerAdapter(CollectionAdapter());
    registerAdapter(PokemonAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CollectedPokemonAdapter());
    registerAdapter(CollectionAdapter());
    registerAdapter(PokemonAdapter());
  }
}
